import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/Hoc/ThemeProvider'
import ReponsiveNav from '@/components/Home/Navbar/ReponsiveNav'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'CV Hieu PC',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      suppressHydrationWarning
      lang='en'
      className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}
    >
      <body className='flex min-h-full flex-col'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='relative min-h-screen overflow-hidden bg-white dark:bg-[#020617]'>
            {/* Background Glow */}
            <div className='pointer-events-none absolute inset-0 z-0 bg-[radial-gradient(125%_125%_at_50%_90%,#ffffff_40%,#ec4899_100%)] dark:bg-[radial-gradient(circle_600px_at_50%_100px,rgba(236,72,153,0.35),transparent)]' />

            {/* Content */}
            <div className='relative z-10 flex min-h-screen flex-col'>
              <ReponsiveNav />
              <main className='flex-1'>{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
